const cellPosition = [
  { x: -9, z: -4 },
  { x: -7, z: -4 },
  { x: -5, z: -4 },
  { x: -3, z: -4 },
  { x: -1, z: -4 },
  { x: 1, z: -4 },
  { x: 3, z: -4 },
  { x: 5, z: -4 },
  { x: 7, z: -4 },
  { x: 9, z: -4 },
  { x: -9, z: -2 },
  { x: -7, z: -2 },
  { x: -5, z: -2 },
  { x: -3, z: -2 },
  { x: -1, z: -2 },
  { x: 1, z: -2 },
  { x: 3, z: -2 },
  { x: 5, z: -2 },
  { x: 7, z: -2 },
  { x: 9, z: -2 },
  { x: -9, z: 0 },
  { x: -7, z: 0 },
  { x: -5, z: 0 },
  { x: -3, z: 0 },
  { x: -1, z: 0 },
  { x: 1, z: 0 },
  { x: 3, z: 0 },
  { x: 5, z: 0 },
  { x: 7, z: 0 },
  { x: 9, z: 0 },
  { x: -9, z: 2 },
  { x: -7, z: 2 },
  { x: -5, z: 2 },
  { x: -3, z: 2 },
  { x: -1, z: 2 },
  { x: 1, z: 2 },
  { x: 3, z: 2 },
  { x: 5, z: 2 },
  { x: 7, z: 2 },
  { x: 9, z: 2 },
  { x: -9, z: 4 },
  { x: -7, z: 4 },
  { x: -5, z: 4 },
  { x: -3, z: 4 },
  { x: -1, z: 4 },
  { x: 1, z: 4 },
  { x: 3, z: 4 },
  { x: 5, z: 4 },
  { x: 7, z: 4 },
  { x: 9, z: 4 },
]
const offset = 0.5 * 1.414
const getCellPosition = (index) => {
  const position = {
    x: cellPosition[index].x,
    z: cellPosition[index].z * 1.414 + offset,
  }
  return position
}
export default getCellPosition
