import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

import Navigation from "../components/Navigation"
import HomeGrid from "../components/Grid/HomeGrid"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>O-ZHU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeGrid />
      <Navigation />
    </div>
  )
}
